version: '3.9'

services:
  tetris:
    container_name: tetris-nginx
    build:
      context: .
    ports:
      - "127.0.0.1:8080:80"
    restart: unless-stopped
    cpus: "0.4"
    mem_reservation: "50M"
    mem_limit: "200M"
